In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score
from sklearn.linear_model import Ridge
from sklearn.polyfeatures import ploynomial
import warnings
warnings.filterwarnings('ignore')



In [46]:
cf = pd.read_csv("car.csv")

In [47]:
cf.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [48]:
cf.tail()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
296     city  2016           9.50           11.6       33988    Diesel   
297     brio  2015           4.00            5.9       60000    Petrol   
298     city  2009           3.35           11.0       87934    Petrol   
299     city  2017          11.50           12.5        9000    Diesel   
300     brio  2016           5.30            5.9        5464    Petrol   

    Seller_Type Transmission  Owner  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0

In [49]:
cf.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [50]:
cf.describe().T

count          mean           std      min      25%      50%  \
Year           301.0   2013.627907      2.891554  2003.00   2012.0   2014.0   
Selling_Price  301.0      4.661296      5.082812     0.10      0.9      3.6   
Present_Price  301.0      7.628472      8.644115     0.32      1.2      6.4   
Kms_Driven     301.0  36947.205980  38886.883882   500.00  15000.0  32000.0   
Owner          301.0      0.043189      0.247915     0.00      0.0      0.0   

                   75%       max  
Year            2016.0    2018.0  
Selling_Price      6.0      35.0  
Present_Price      9.9      92.6  
Kms_Driven     48767.0  500000.0  
Owner              0.0       3.0

In [51]:
cf.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [52]:
cf.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [53]:
cf

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [54]:
cf['Transmission'].value_counts()

Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [55]:
cf.drop(['Car_Name'],axis=1,inplace=True)


In [56]:
carr = cf.select_dtypes(include=object).columns
carr

Index(['Fuel_Type', 'Seller_Type', 'Transmission'], dtype='object')

In [57]:
carr

Index(['Fuel_Type', 'Seller_Type', 'Transmission'], dtype='object')

In [58]:
lab_enc = LabelEncoder()
for i in carr:
    cf[i] = lab_enc.fit_transform(cf[i])

In [59]:
cf.head()

Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  \
0  2014           3.35           5.59       27000          2            0   
1  2013           4.75           9.54       43000          1            0   
2  2017           7.25           9.85        6900          2            0   
3  2011           2.85           4.15        5200          2            0   
4  2014           4.60           6.87       42450          1            0   

   Transmission  Owner  
0             1      0  
1             1      0  
2             1      0  
3             1      0  
4             1      0

In [60]:
cf

Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  \
0    2014           3.35           5.59       27000          2            0   
1    2013           4.75           9.54       43000          1            0   
2    2017           7.25           9.85        6900          2            0   
3    2011           2.85           4.15        5200          2            0   
4    2014           4.60           6.87       42450          1            0   
..    ...            ...            ...         ...        ...          ...   
296  2016           9.50          11.60       33988          1            0   
297  2015           4.00           5.90       60000          2            0   
298  2009           3.35          11.00       87934          2            0   
299  2017          11.50          12.50        9000          1            0   
300  2016           5.30           5.90        5464          2            0   

     Transmission  Owner  
0               1      0  
1               1      0  
2               1      0  
3               1      0  
4               1      0  
..            ...    ...  
296             1      0  
297             1      0  
298             1      0  
299             1      0  
300             1      0  

[301 rows x 8 columns]

In [61]:
X = cf.drop('Selling_Price',axis=1)
y = cf['Selling_Price']



In [62]:
X

Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
0    2014           5.59       27000          2            0             1   
1    2013           9.54       43000          1            0             1   
2    2017           9.85        6900          2            0             1   
3    2011           4.15        5200          2            0             1   
4    2014           6.87       42450          1            0             1   
..    ...            ...         ...        ...          ...           ...   
296  2016          11.60       33988          1            0             1   
297  2015           5.90       60000          2            0             1   
298  2009          11.00       87934          2            0             1   
299  2017          12.50        9000          1            0             1   
300  2016           5.90        5464          2            0             1   

     Owner  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
296      0  
297      0  
298      0  
299      0  
300      0  

[301 rows x 7 columns]

In [63]:
y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [64]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [65]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()


x_train_scaled = min_max_scaler.fit_transform(x_train)


x_test_scaled = min_max_scaler.transform(x_test)


In [66]:
# # normalise
# st_scaler = StandardScaler()
# scaled_x = st_scaler.fit_transform(x)
# scaled_x

In [67]:
# split into training and testing


In [68]:
print(x_test.shape,y_test.shape)

(76, 7) (76,)


In [69]:
print(x_train.shape,y_train.shape)

(225, 7) (225,)


In [70]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(x_train_scaled,y_train)

LinearRegression()

In [71]:
y_pred = lr_model.predict(x_test_scaled)

In [72]:
y_pred

array([ 7.08116375, -0.34778693,  4.39251189,  8.50523618, 13.59916378,
        4.96959079,  3.6817552 ,  1.42213013,  5.28281471,  4.76767283,
        2.45405739,  1.59177671,  5.15899397,  7.42622454,  8.12314599,
       13.71297994,  7.19613038,  4.3895981 , -0.36980919,  2.32342099,
        4.96164592,  3.92199269,  6.35380065,  8.07735211, -1.7565571 ,
        1.89633988, -0.69665759,  0.84096003,  0.05928392,  7.05995048,
        3.20015998,  6.98246085,  0.74593109,  7.43831094,  3.74052139,
        1.78220493,  5.64275408,  6.53617338, -2.53755306,  8.62434016,
        8.66353145, 19.12602755,  4.48980405,  3.9915907 ,  6.22763143,
        9.33204033,  0.17817227,  1.65724807,  5.26152047,  6.88559389,
        7.93197487,  4.29247302,  5.02356072, 19.46935113,  1.73738094,
        1.31403762,  0.33219424,  2.21678119,  3.57229229,  0.87053628,
        3.77228163,  6.40821944,  2.74947891, 20.52433162,  4.43996868,
        5.6658022 ,  8.63021203,  7.37673834,  2.99056068,  2.81

In [73]:
y_test

223     8.25
150     0.50
226     5.25
296     9.50
52     18.00
       ...  
46      2.65
158     0.48
230     6.15
179     0.31
27      6.00
Name: Selling_Price, Length: 76, dtype: float64

In [75]:
r2_score(y_test,y_pred)*100

86.19745435370257

In [ ]:
lasso = Lasso()
lasso.fit(x_train_scaled,y_train)

Lasso()

In [ ]:
y_pred = lasso.predict(x_test_scaled)

In [ ]:
y_pred[:10]

array([4.96809859, 3.56927711, 4.96809859, 4.96809859, 4.96809859,
       4.96809859, 4.96809859, 3.56927711, 4.96809859, 4.96809859])

In [ ]:
y_test[:10]

223     8.25
150     0.50
226     5.25
296     9.50
52     18.00
261     5.50
246     3.75
166     0.45
221     4.50
215     4.50
Name: Selling_Price, dtype: float64

In [ ]:
r2_score(y_test,y_pred)

0.08574190834515272

In [ ]:
from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(x_train,y_train)

Ridge()

In [ ]:
ridge_pred = ridge.predict(x_test)
ridge_pred[:10]

array([ 7.06060621, -0.34138014,  4.39220723,  8.48668293, 13.52585691,
        4.96894734,  3.67781702,  1.43984763,  5.21075343,  4.76912077])

In [ ]:
r2_score(ridge_pred,y_test)

0.7661624490080399

In [ ]:
ridge.score(x_train,y_train)

0.8796750713763593

In [ ]:
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor(n_estimators=10)
forest.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10)

In [ ]:
forest_pred = forest.predict(x_test)
forest_pred

array([ 6.59 ,  0.47 ,  4.71 , 10.099, 15.471,  5.31 ,  3.16 ,  0.465,
        3.865,  4.93 ,  2.99 ,  0.801,  4.84 ,  6.57 ,  7.64 , 15.211,
        6.205,  4.015,  0.47 ,  1.71 ,  3.2  ,  4.96 ,  5.435, 10.001,
        0.219,  0.73 ,  0.289,  0.806,  0.495,  4.695,  2.36 ,  5.795,
        0.475,  7.63 ,  3.785,  1.155,  5.61 ,  5.505,  0.285,  8.174,
        8.784, 21.075,  4.97 ,  4.855,  5.72 , 11.13 ,  0.226,  0.9  ,
        5.625,  6.785,  6.439,  3.045,  5.605, 22.35 ,  1.192,  1.173,
        0.409,  2.705,  3.695,  2.77 ,  4.369,  6.145,  3.045, 22.35 ,
        4.545,  6.07 , 10.724,  5.885,  0.453,  3.06 ,  2.83 ,  2.605,
        0.462,  5.535,  0.469,  5.31 ])

In [ ]:
r2_score(forest_pred,y_test)

0.8926451155928072

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3)

In [ ]:
x_test.shape,x_train.shape

((91, 7), (210, 7))

In [ ]:
y_test.shape,y_train.shape

((91,), (210,))

In [ ]:
from sklearn.linear_model import LinearRegression
lin_model = LinearRegression()
lin_model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred  = lin_model.predict(x_test)
y_pred

array([ 4.27201509,  6.43286707,  3.72380502,  0.63147947, 16.89275555,
        9.73714469, 10.77518713,  4.21115933,  6.5707036 ,  0.75570494,
        4.28734228, 18.36036727,  4.19973001,  6.99118598,  4.31579447,
       14.49278062,  4.89243787, -0.40970002,  8.17298347,  1.64104004,
        1.40444933, -0.64972574, -3.52895037,  4.30743828,  1.16622816,
       20.08475904,  6.63980055,  6.20775245,  5.53450789,  4.21344267,
        2.51015992,  0.57242848,  7.62715918,  2.13695374,  3.50493599,
        9.81713576,  7.06310788,  4.99563938, 20.24577722,  2.92823812,
       -3.94087004,  1.47151156, -0.70434881,  0.60562756,  3.78963582,
        1.31743956, 10.23061181,  7.69471719, 12.04903777, -2.67968526,
        0.90801943,  7.712679  ,  2.89929429,  7.42430867,  7.93633424,
        2.75579729,  8.88390396,  5.90853198,  1.36492945,  2.53942638,
        3.39187221,  4.25980285,  1.8861539 ,  4.5793719 ,  0.24127321,
        5.38906377,  0.07219023,  2.81425704,  5.14345171,  9.11

In [ ]:
y_test

202     4.40
265     6.50
204     2.75
195     0.18
79     14.50
       ...  
148     0.52
11      6.85
241     4.75
169     0.40
165     0.45
Name: Selling_Price, Length: 91, dtype: float64

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)*100

84.67061998002558

In [ ]:
lin_model.score(x_train,y_train)

0.8787940313275374

In [ ]:
# testing accuracy
lin_model.score(x_test,y_test)

0.8467061998002557